# Generated by Django 5.0.4 on 2024-04-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residents',
            fields=[
                ('resident_id', models.AutoField(primary_key=True, serialize=False)),
                ('resident_first_name', models.CharField(max_length=100)),
                ('resident_last_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=200)),
                ('relation1', models.CharField(max_length=100)),
                ('contact_name2', models.CharField(max_length=200)),
                ('relation2', models.CharField(max_length=100)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('work_number', models.CharField(max_length=20)),
                ('cell_number', models.CharField(max_length=20)),
                ('fax_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('address_contact2', models.CharField(max_length=255)),
                ('city_contact2', models.CharField(max_length=100)),
                ('province_contact2', models.CharField(max_length=100)),
                ('postal_code_contact2', models.CharField(max_length=20)),
                ('phone_number_contact2', models.CharField(max_length=20)),
                ('work_number_contact2', models.CharField(max_length=20)),
                ('cell_number_contact2', models.CharField(max_length=20)),
                ('fax_number_contact2', models.CharField(max_length=20)),
                ('email_address_contact2', models.EmailField(max_length=254)),
                ('notes', models.TextField()),
                ('room_number', models.CharField(max_length=50)),
                ('ohip', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('dnr', models.BooleanField(default=False)),
                ('allergies', models.BooleanField(default=False)),
                ('allergies_info', models.TextField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('weight_last', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('blood_pressure_last', models.CharField(blank=True, max_length=20, null=True)),
                ('admission_date', models.DateField()),
            ],
        ),
    ]
