# Generated by Django 5.0.4 on 2024-04-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='type',
            field=models.CharField(choices=[('Withdrawl', 'Withdrawl'), ('Deposit', 'Deposit')], default='', max_length=20),
        ),
    ]
