# Generated by Django 5.0.4 on 2024-04-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorApp', '0002_alter_residents_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
