# Generated by Django 5.0.4 on 2024-05-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorApp', '0002_residents_poa_alter_rentalfee_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residents',
            old_name='poa',
            new_name='poa_contact1',
        ),
        migrations.AddField(
            model_name='residents',
            name='poa_contact2',
            field=models.CharField(choices=[('POA Care', 'POA Care'), ('POA Financial', 'POA Financial'), ('POA Financial & Care', 'POA Financial & Care')], default='POA Care', max_length=100, null=True),
        ),
    ]
