# Generated by Django 5.0.4 on 2024-04-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorApp', '0003_alter_residents_security_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents',
            name='date_of_birth',
            field=models.DateTimeField(default='1990-01-01 00:00:00', null=True),
        ),
    ]
