# Generated by Django 5.0.4 on 2024-04-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorApp', '0003_alter_pettycash_deposit_alter_pettycash_withdrawl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalfee',
            name='month',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Jan', max_length=10, null=True),
        ),
    ]
