# Generated by Django 5.0.4 on 2024-06-04 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorApp', '0003_rename_poa_residents_poa_contact1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emailed_report_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_body', models.TextField()),
                ('date', models.DateField()),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seniorApp.residents')),
            ],
        ),
    ]
