# Generated by Django 5.0.4 on 2024-04-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorApp', '0004_alter_residents_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents',
            name='admission_date',
            field=models.DateTimeField(default='1990-01-01 00:00:00', null=True),
        ),
    ]
