# Generated by Django 5.0.4 on 2024-04-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorApp', '0004_alter_rentalfee_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycash',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='withdrawl',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
