# Generated by Django 5.0.4 on 2024-06-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorApp', '0004_emaillogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residents',
            name='poa_contact1',
            field=models.CharField(choices=[('POA Care', 'POA Care'), ('POA Financial', 'POA Financial'), ('POA Financial & Care', 'POA Financial & Care'), ('None', 'N/A')], default='POA Care', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='residents',
            name='poa_contact2',
            field=models.CharField(choices=[('POA Care', 'POA Care'), ('POA Financial', 'POA Financial'), ('POA Financial & Care', 'POA Financial & Care'), ('None', 'N/A')], default='POA Care', max_length=100, null=True),
        ),
    ]
