# Generated by Django 5.0.4 on 2024-06-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seniorApp', '0005_alter_residents_poa_contact1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residents',
            old_name='poa_contact1',
            new_name='POA_contact1',
        ),
        migrations.RenameField(
            model_name='residents',
            old_name='poa_contact2',
            new_name='POA_contact2',
        ),
    ]
