# Generated by Django 5.0.4 on 2024-06-20 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seniorApp', '0006_rename_poa_contact1_residents_poa_contact1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residents',
            old_name='dnr',
            new_name='DNR',
        ),
    ]
