# Generated by Django 5.0.4 on 2024-04-17 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorApp', '0006_pettycashtype_pettycash_rentalfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='petty_cash_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seniorApp.pettycashtype'),
        ),
    ]
