# Generated by Django 5.0.4 on 2024-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seniorApp', '0007_rename_dnr_residents_dnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillogs',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
